from rest_framework import serializers
from .models import PhotoSession

class PhotoSessionSerializer(serializers.ModelSerializer):
    class Meta:
        model = PhotoSession
        fields = [
            'id', 
            'photo_1', 
            'photo_2', 
            'photo_3', 
            'photo_4', 
            'composite_frame', 
            'gif_video', 
            'qr_code', 
            'created_at'
        ]
        # These fields are generated by the backend, so the frontend cannot modify them.
        read_only_fields = ['id', 'composite_frame', 
                            'gif_video', 'qr_code',
                            'created_at']
