# Generated by Django 6.1.1 on 2026-09-20 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_1', models.ImageField(upload_to='photobooth/raw_photos/')),
                ('photo_2', models.ImageField(upload_to='photobooth/raw_photos/')),
                ('photo_3', models.ImageField(upload_to='photobooth/raw_photos/')),
                ('photo_4', models.ImageField(upload_to='photobooth/raw_photos/')),
                ('composite_frame', models.ImageField(blank=True, null=True, upload_to='photobooth/frames/')),
                ('gif_video', models.FileField(blank=True, null=True, upload_to='photobooth/gifs/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='photobooth/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
